- ambari-metrics-timelineservice/pom.xml
- pom.xml
Backport: Ambari 25203 branch 2.7 (#2896) from benyoka
Only back port for now
> AMBARI-25203 Updated jackson-databind to 2.9.8 and boucycastle libs to 1.61

- ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/loadsimulator/data/AppID.java
Changed the AppId to match the data file names metrics_def/HBASE_REGIONSERVER.dat and metrics_def/HBASE_MASTER.dat
build and executed data simulator start command  as below, there was no NPE
`bin % ./start.sh  localhost:6188 2`
> AMBARI-25808: Metrics data simulator throws NPE

- ambari-metrics-host-monitoring/pom.xml
- pom.xml
manually tested this patch.
Run below two commands before and after the fix
```
mvn clean install -DskipPythonTests
mvn clean install -DskipTests
```
After the fix both commands skip the python tests, that is what is expected
> AMBARI-25810: Allow skipping Python unit tests in ambari-metrics

- pom.xml
Upgrade maven-assembly-plugin from 2.2-beta-5 to 3.4.2(latest version).
This reduces the ambari metrics build time from 10 min to 2 min
Built before and after the change and observed the build time reduction.
Please refer https://issues.apache.org/jira/browse/AMBARI-25811 for detail
> AMBARI-25811: Optimize ambari metrics build time

- ambari-metrics-common/pom.xml
> AMBARI-25822: Remove invalid relocations in pom.xml for ambari-metrics-common

- pom.xml
Successful setup Ambari-Metrics after upgrade grafana from 6.7.4 to 9.3.2.
> AMBARI-25830: Upgrade AMS Grafana version to 9.3.2

- ambari-metrics-kafka-sink/src/test/java/org/apache/hadoop/metrics2/sink/kafka/KafkaTimelineMetricsReporterTest.java
> AMBARI-25866: Fix an unit test failure on ambari-metrics-kafka-sink

- ambari-metrics-common/pom.xml
Fix unit test failure on ambari-metrics-common due to the lack of a dependency.
Ran the following command locally.
```
$ mvn clean test -f ambari-metrics-common/pom.xml
...
Results :
Tests run: 20, Failures: 0, Errors: 0, Skipped: 0
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.588 s
[INFO] Finished at: 2023-02-24T15:17:23+09:00
[INFO] ------------------------------------------------------------------------
```
> AMBARI-25864: Fix an unit test failure on ambari-metrics-common

- ambari-metrics-host-monitoring/pom.xml
- ambari-metrics-host-monitoring/src/test/python/unitTests.py
Currently, we have a unit test failure in ambari-metrics-host-monitoring, as follows:
```
$ mvn clean test -f ambari-metrics-host-monitoring/pom.xml
...
[INFO] --- exec-maven-plugin:1.2.1:exec (python-test) @ ambari-metrics-host-monitoring ---
Running tests
Traceback (most recent call last):
File "unitTests.py", line 137, in <module>
sys.exit(main())
File "unitTests.py", line 106, in main
modules]
File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
module = __import__('.'.join(parts_copy))
File "/home/sekikn/repos/ambari-metrics/ambari-metrics-host-monitoring/src/test/python/core/TestHostInfo.py", line 24, in <module>
from host_info import HostInfo
File "/home/sekikn/repos/ambari-metrics/ambari-metrics-host-monitoring/src/main/python/core/host_info.py", line 25, in …
```
> AMBARI-25865: Fix an unit test failure on ambari-metrics-host-monitoring

- ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/discovery/TimelineMetricMetadataSync.java
- ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/discovery/TestMetadataSync.java
Compare not only host but also list of apps associated with the host
Test the scenario mentioned the jira before and after the fix. Fix was verified on by applying the changes on existing cluster
> AMBARI-25962: Host apps metadata is not synced to other collectors when multiple collectors are installed

- ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/discovery/TimelineMetricMetadataManager.java
- ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/discovery/TimelineMetricMetadataSync.java
- ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/discovery/TestMetadataSync.java
When metrics are synced from other collectors, update the uuid metrics metadata map as well.
Tested the scenario mentioned the jira before and after the fix. Fix was verified by applying the changes on existing cluster
> AMBARI-25963: Metrics metadata sync problem, accessing metrics which got created though other collector throws NPE

- ambari-metrics-timelineservice/pom.xml
ambari-metrics build failed, the error massage is:
The high version of maven-dependency-plugin  do not support "includeScope" and "excludeScope"  label at the same time.
build ambari-metrics project:
mvn clean package -Dbuild-rpm -Drat.skip=true -DskipTests -Dmaven.test.skip=true
> AMBARI-26123：Ambari-metrics build failed

- pom.xml
Upgrade Grafana version 9.5.5 to 11.1.4 to fix CVE-2024-1442
Tested it by installing a local cluster. All metrics are coming. Check images on https://issues.apache.org/jira/browse/AMBARI-26095
> [AMBARI-26095] Upgrade Grafana version 9.5.5 to 11.1.4

- ambari-metrics-grafana/conf/unix/ambari-metrics-grafana
When running the ambari-metrics-grafana status,
/usr/sbin/ambari-metrics-grafana: line 177: status: command not found
> AMBARI-26016:  ambari-metrics-grafana status,command not found

- pom.xml
Problem: [build](https://github.com/apache/ambari-metrics/actions/runs/11707520404/job/32845254675#step:6:486) tries to download release artifacts from `apache-snapshots` repo, and non-Apache artifacts from `apache-releases` repo.
```
[INFO] Downloading from apache-releases: https://repository.apache.org/content/repositories/releases/com/google/guava/guava/28.0-jre/guava-28.0-jre.pom
[INFO] Downloading from apache-snapshots: https://repository.apache.org/content/repositories/snapshots/com/google/guava/guava/28.0-jre/guava-28.0-jre.pom
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/com/google/guava/guava/28.0-jre/guava-28.0-jre.pom
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/google/guava/guava/28.0-jre/guava-28.0-jre.pom (8.7 kB at 513 …
```
> AMBARI-26264. Disable releases for apache-snapshots repo

- .github/workflows/ambari.yml
- ambari-metrics-assembly/pom.xml
- ambari-metrics-common/pom.xml
- ambari-metrics-flume-sink/pom.xml
- ambari-metrics-hadoop-sink/pom.xml
- ambari-metrics-host-aggregator/pom.xml
- ambari-metrics-host-aggregator/src/test/java/org/apache/hadoop/metrics2/host/aggregator/AggregatorWebServiceTest.java
- ambari-metrics-host-monitoring/pom.xml
- ambari-metrics-kafka-sink/pom.xml
- ambari-metrics-storm-sink/pom.xml
- ambari-metrics-timelineservice/pom.xml
- ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/webapp/TestTimelineWebServices.java
- pom.xml
Revert "AMBARI-26142: JDK17 support for Ambari-metrics (#134)"
This reverts commit 667fa9acc5aa96b50245b7be0d862b26815ac45e.
Reason for revert:
The JDK17 upgrade for Ambari-metrics has caused compatibility issues with various component sinks (Hadoop, HBase, etc.) that are still running on JDK8. Since Ambari-metrics produces JAR files that serve as plugins for these components, the JDK17-compiled sinks are not compatible with the JDK8 runtime environment of the host components.
Specifically, when Hadoop (which runs on JDK8) attempts to load the metrics sink compiled with JDK17, it fails to start due to bytecode incompatibility issues. This incompatibility affects multiple components that integrate with Ambari-metrics.
We need to revert to the JDK8-compatible version until we can implement …
> Revert "AMBARI-26142: JDK17 support for Ambari-metrics"

- ambari-metrics-host-monitoring/src/main/python/core/emitter.py
- ambari-metrics-host-monitoring/src/main/python/core/metering.py
- ambari-metrics-host-monitoring/src/main/python/core/metric_collector.py
- ambari-metrics-host-monitoring/src/main/python/core/spnego_kerberos_auth.py
Fix python3 import error
before this patch
after this patch
> AMBARI-26327: Fix ambari-metrics-monitor start failure

- ambari-metrics-timelineservice/pom.xml
Exclude servlet-api from hbase-testing-util to resolve the jar conflict problem
manual test
> AMBARI-26339: Exclude servlet-api from hbase-testing-util

- .github/workflows/ambari.yml
- ambari-metrics-timelineservice/pom.xml
Ambari-metrics use GitHub Action Ubutnu 20.04 workers but the runner image is no longer available after April 15th. This pull request change updating the .github/workflows/ambari.yml file to set runs-on: ubuntu-22.04.
mvn dependency:tree
> AMBARI-26477: Ambari-metrics precommit must migrate away from Ubuntu 20.04

- ambari-metrics-timelineservice/pom.xml
change jettison version from 1.1 to 1.5.4
```
cd ambari-metrics-timelineservice     
mvn dependency:tree -DignoreErrors | grep jettison  
```   
> AMBARI-26488:Bump jettison from 1.1 to 1.5.4 in /ambari-metrics-timelineservice

- ambari-metrics-host-monitoring/src/main/python/core/controller.py
- ambari-metrics-host-monitoring/src/main/python/core/emitter.py
- ambari-metrics-host-monitoring/src/main/python/core/metering.py
- ambari-metrics-host-monitoring/src/main/python/core/metric_collector.py
- ambari-metrics-host-monitoring/src/main/python/core/spnego_kerberos_auth.py
- ambari-metrics-host-monitoring/src/main/python/main.py
- ambari-metrics-host-monitoring/src/test/python/core/TestEmitter.py
- ambari-metrics-host-monitoring/src/test/python/core/TestHostInfo.py
Fix incorrect Python import names.
pip3 install distro
yum install -y krb5-devel python3-devel gcc
pip3 install kerberos
cd ambari-metrics-host-monitoring/src/test/python
export PYTHONPATH=../../main/python:$PYTHONPATH
python3 unitTests.py
> AMBARI-26484: Ambari-metrics python test failures.

- BUILD.md
- ambari-metrics-assembly/pom.xml
Add a Maven rpm.arch property to specify rpm build architecture.
On x86 Rocky8:
mvn clean package -Prpm  -DskipTests
On aarch64 Rocky8:
mvn clean package -Prpm -Drpm.arch=aarch64 -DskipTests
Both built RPMs for the corresponding platform.
> AMBARI-26483: Enable ARM64 RPM for Ambari Metrics.

- ambari-metrics-host-aggregator/pom.xml
Bump jetty-server, jetty-webapp in ambari-metrics-host-aggregator to the latest 9.4.57
Build, existing UT.
> AMBARI-26450: Update ambari-metrics jetty version to 9.4.57
