apache/ambari-metrics

ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/PhoenixHBaseAccessor.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/discovery/TimelineMetricMetadataManager.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/DefaultCondition.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/MetadataQueryCondition.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/PhoenixTransactSQL.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/TransientMetricCondition.java, ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/discovery/TestMetadataManager.java
Add support for wildcards in appId and instanceId
Manually tested.
Added unit test.
=> [AMBARI-24723] Support wild cards in AppId and InstanceId fields in AMS GET API.

ambari-metrics-grafana/ambari-metrics/datasource.js, ambari-metrics-grafana/ambari-metrics/query_ctrl.js
In the new grafana version templateSrv object doesn't have some fields. We need to get these values from a different property.
=> [AMBARI-24738] Update grafana datasource to get values from new object.

ambari-metrics-grafana/ambari-metrics/query_ctrl.js, ambari-metrics-grafana/ambari-metrics/query_ctrl.ts
Fixed issues related to creating a new dashboard
=> [AMBARI-24884] AMS Grafana query editor panel does not work in upgraded version.

ambari-metrics-assembly/pom.xml, ambari-metrics-assembly/src/main/assembly/monitor.xml, ambari-metrics-grafana/ambari-metrics/datasource.js, ambari-metrics-host-aggregator/src/main/java/org/apache/hadoop/metrics2/sink/timeline/AggregatedMetricsPublisher.java, ambari-metrics-host-monitoring/conf/unix/instance_type_provider_azure, ambari-metrics-host-monitoring/conf/unix/instance_type_provider_ec2, ambari-metrics-host-monitoring/conf/unix/instance_type_provider_gce, ambari-metrics-host-monitoring/src/main/python/core/application_metric_map.py, ambari-metrics-host-monitoring/src/main/python/core/config_reader.py, ambari-metrics-host-monitoring/src/main/python/core/controller.py, ambari-metrics-host-monitoring/src/main/python/core/instance_type_provider.py, ambari-metrics-host-monitoring/src/main/python/core/metering.py, ambari-metrics-host-monitoring/src/main/python/core/metric_collector.py, ambari-metrics-host-monitoring/src/test/python/core/TestMetricCollector.py, ambari-metrics-timelineservice/conf/unix/metrics_whitelist, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/aggregators/TimelineMetricClusterAggregator.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/aggregators/TimelineMetricHostAggregator.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/aggregators/v2/TimelineMetricClusterAggregator.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/aggregators/v2/TimelineMetricFilteringHostAggregator.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/aggregators/v2/TimelineMetricHostAggregator.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/PhoenixTransactSQL.java, ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/aggregators/ITMetricAggregator.java
Add cloud provider based metering metric framework for AMS metric monitor.
Manually tested.
=> [AMBARI-25078] Add metering metrics to AMS Metric Monitor.

ambari-metrics-grafana/ambari-metrics/datasource.js, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/MetadataQueryCondition.java, ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/discovery/TestMetadataManager.java
Fix the issue with handling of instanceId parameter.
Manually tested.
=> [AMBARI-25089] NIFI-Hosts dashboard does not show any metrics in Grafana

pom.xml
Forward port commit [3eaa7d4](https://github.com/apache/ambari/commit/3eaa7d4e5c0834f5011627769d3155d5c317046a) on ambari branch-2.7
=> AMBARI-25311: FinalizeKerberosServerAction timeout has to be configurable

ambari-metrics-timelineservice/pom.xml
AMBARI-25337. Update HDP dependencies of AMS for 2.7.4.
backport 
=> AMBARI-25337. Update HDP dependencies of AMS for 2.7.4.

ambari-metrics-common/src/main/java/org/apache/hadoop/metrics2/sink/timeline/AbstractTimelineMetricsSink.java, ambari-metrics-common/src/test/java/org/apache/hadoop/metrics2/sink/timeline/AbstractTimelineMetricSinkTest.java
AMBARI-25400 Issue while determining live collector in case of HA
=> AMBARI-25400 Issue while determining live collector in case of HA

ambari-metrics-common/src/main/java/org/apache/hadoop/metrics2/sink/timeline/AppCookieManager.java, ambari-metrics-hadoop-sink/src/main/java/org/apache/hadoop/metrics2/sink/timeline/HadoopTimelineMetricsSink.java, ambari-metrics-host-aggregator/src/main/java/org/apache/hadoop/metrics2/host/aggregator/AggregatorApplication.java, ambari-metrics-kafka-sink/src/main/java/org/apache/hadoop/metrics2/sink/kafka/KafkaTimelineMetricsReporter.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/HBaseTimelineMetricsService.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/TimelineMetricStoreWatcher.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/aggregators/AbstractTimelineAggregator.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/DefaultCondition.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/DefaultPhoenixDataSource.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/MetadataQueryCondition.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/AbstractPhoenixMetricsCopier.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/MetricsDataMigrationLauncher.java
AMBARI-25516. Missing @OverRide on methods
=> AMBARI-25516. Missing @Override on methods

ambari-metrics-assembly/pom.xml, ambari-metrics-grafana/ambari-metrics/datasource.js, ambari-metrics-grafana/ambari-metrics/plugin.json
AMBARI-25379 Fix 'All' selection regarding templated variables
backport 
=> AMBARI-25379 Upgrade AMS Grafana version to 6.4.2

ambari-metrics-kafka-sink/src/main/java/org/apache/hadoop/metrics2/sink/kafka/JvmMetricSet.java, ambari-metrics-kafka-sink/src/main/java/org/apache/hadoop/metrics2/sink/kafka/KafkaTimelineMetricsReporter.java, ambari-metrics-kafka-sink/src/main/java/org/apache/hadoop/metrics2/sink/kafka/MetricNameBuilder.java, ambari-metrics-kafka-sink/src/test/java/org/apache/hadoop/metrics2/sink/kafka/JvmMetricSetTest.java
AMBARI-25402 Please provide jvm metrics for kafka components in Ambari (forward)
=> AMBARI-25402 Please provide jvm metrics for kafka components in Ambari

ambari-metrics-grafana/ambari-metrics/datasource.js, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/PhoenixHBaseAccessor.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/query/TransientMetricCondition.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/uuid/HashBasedUuidGenStrategy.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/uuid/MD5UuidGenStrategy.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/uuid/MetricUuidGenNullRestrictedStrategy.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/uuid/Murmur3HashUuidGenStrategy.java, ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/uuid/MetricUuidGenStrategyTest.java
Forward 5fd23256c7e0cbba78cee8d8883c00c34e70ff56  AMBARI-25563. Storm dashboards are not showing metrics.
=> AMBARI-25563. Storm dashboards are not showing metrics.

ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/AbstractPhoenixMetricsCopier.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/MetricsDataMigrationLauncher.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/PhoenixClusterMetricsCopier.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/PhoenixHostMetricsCopier.java
AMBARI-25569 Reassess Ambari Metrics data migration
=> AMBARI-25569 Reassess Ambari Metrics data migration

ambari-metrics-timelineservice/pom.xml, pom.xml
Forward port commit [2e60a76](https://github.com/apache/ambari/commit/2e60a76ced3e4ecf1c4356c9727821fe66e8986c) on ambari branch-2.7
=> AMBARI-25599: Consider to eliminate HDP public binary references

ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/availability/MetricCollectorHAController.java, ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/availability/MetricCollectorHAControllerTest.java
Forward port commit [9938407](https://github.com/apache/ambari/commit/99384078da451f65ed670fa8a378d91ce46f81bf) on ambari branch-2.7
=> AMBARI-25635: Clear Cluster and METRIC_AGGREGATORS MBeans upon shutdown

ambari-metrics-common/pom.xml, ambari-metrics-timelineservice/pom.xml
Forward port commit [c950b4d](https://github.com/apache/ambari/commit/c950b4d409dacf15049039858c77794e0ec96eb9) on ambari branch-2.7
=> AMBARI-25722: Remediation of log4j dependency’s

ambari-metrics-assembly/pom.xml, ambari-metrics-timelineservice/pom.xml, pom.xml
Forward port commit [893f3f8](https://github.com/apache/ambari/commit/893f3f85cf25c748167455fbcebe6b90512d067c) on ambari branch-2.7
This PR relies on #67 
=> AMBARI-25668: Integrate the Apache released HBase as back store of Ambari Metrics

ambari-metrics-timelineservice/pom.xml, ambari-metrics-timelineservice/src/test/java/org/apache/ambari/metrics/core/timeline/AbstractMiniHBaseClusterTest.java, pom.xml
Forward port commit [de81655](https://github.com/apache/ambari/commit/de816551198151ec3e54ae228e633cfb1c97eb01) on ambari branch-2.7
=> AMBARI-25717: Fix broken build

ambari-metrics-timelineservice/pom.xml, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/records/impl/pb/ApplicationAttemptFinishDataPBImpl.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/records/impl/pb/ApplicationAttemptStartDataPBImpl.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/records/impl/pb/ApplicationFinishDataPBImpl.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/records/impl/pb/ApplicationStartDataPBImpl.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/records/impl/pb/ContainerFinishDataPBImpl.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/records/impl/pb/ContainerStartDataPBImpl.java, pom.xml
AMBARI-25780: Ambari metrics should upgrade hadoop and hbase for known CVE issues
=> AMBARI-25780 Ambari metrics should upgrade hadoop and hbase for known CVE issues

.github/pull_request_template.md, README.md, ambari-metrics-assembly/pom.xml, ambari-metrics-host-monitoring/pom.xml, ambari-metrics-kafka-sink/src/main/java/org/apache/hadoop/metrics2/sink/kafka/KafkaTimelineMetricsReporter.java, ambari-metrics-storm-sink/pom.xml, ambari-metrics-timelineservice/pom.xml, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/AbstractPhoenixMetricsCopier.java, ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/upgrade/core/PhoenixClusterMetricsCopier.java, pom.xml
Fix syntax, refactor and versions and make `mvn package`  build pass
=> AMBARI-25782: Fix syntax, refactor and versions after forwarding from Ambari to ambari-metrics

ambari-metrics-host-monitoring/src/main/python/core/emitter.py, ambari-metrics-host-monitoring/src/main/python/core/stop_handler.py, ambari-metrics-timelineservice/conf/unix/ambari-metrics-collector
=> AMBARI-25821: Fixed syntax error that caused OOM in the ambari-metrics-collector

ambari-metrics-timelineservice/conf/unix/ambari-metrics-collector
=> AMBARI-25834: Fix syntax errors for ambari-metrics-collector

ambari-metrics-assembly/pom.xml
=> AMBARI-25840: Optimized rpm packaging for the Ambari-Metric-Collector

ambari-metrics-assembly/pom.xml, ambari-metrics-common/pom.xml, ambari-metrics-flume-sink/pom.xml, ambari-metrics-grafana/pom.xml, ambari-metrics-hadoop-sink/pom.xml, ambari-metrics-host-aggregator/pom.xml, ambari-metrics-host-monitoring/pom.xml, ambari-metrics-kafka-sink/pom.xml, ambari-metrics-storm-sink/pom.xml, ambari-metrics-timelineservice/pom.xml, pom.xml
=> AMBARI-25859: Correct Ambari Metrics version parsing logic

.github/workflows/ambari.yml
This PR introduces minimal CI job for Ambari Metrics.
Tested on my own ambari-metrics repository. https://github.com/sekikn/ambari-metrics/actions/runs/4268110274/jobs/7430349846
=> AMBARI-25867: Introduce CI build for Ambari Metrics

ambari-metrics-assembly/pom.xml, ambari-metrics-common/pom.xml, ambari-metrics-flume-sink/pom.xml, ambari-metrics-grafana/pom.xml, ambari-metrics-hadoop-sink/pom.xml, ambari-metrics-host-aggregator/pom.xml, ambari-metrics-host-monitoring/pom.xml, ambari-metrics-kafka-sink/pom.xml, ambari-metrics-storm-sink/pom.xml, ambari-metrics-timelineservice/pom.xml, pom.xml
=> AMBARI-25876: Bump version to 3.0.0-SNAPSHOT

ambari-metrics-timelineservice/src/main/resources/metrics_def/AMSSMOKETESTFAKE.DAT, ambari-metrics-timelineservice/src/main/resources/metrics_def/TIMELINE_METRIC_STORE_WATCHER.DAT
content of AMSSMOKETESTFAKE.DAT AMSSMOKETESTFAKE.dat is same.
Also the content of TIMELINE_METRIC_STORE_WATCHER.DAT and TIMELINE_METRIC_STORE_WATCHER.dat is same.
Deleted AMSSMOKETESTFAKE.DAT and TIMELINE_METRIC_STORE_WATCHER.DAT
simple change, to verify I will clone the repo again after changes are merged.
=> AMBARI-25803: ambari and ambari-metrics repo cloning logs warning because of case sensitive files

ambari-metrics-grafana/pom.xml
made code changes, built ambari metrics, verified amabri metrics grafana rpm includes all files
=> AMBARI-25959: Ambari Metrics Grafana rpm missing some grafana tarball files

ambari-metrics-grafana/ambari-metrics/datasource.js
Bring the same changes as done by [AMBARI-20391](https://issues.apache.org/jira/browse/AMBARI-20391) in branch-2
Applied the changes on existing cluster. Snapshot are attached on this issue jira
=> AMBARI-25957: Ambari Metrics Grafana Datasource is not working

ambari-metrics-grafana/ambari-metrics/datasource.js
Made changes required to adapt grafna upgrade from 6.x to 9.x
Verified and attached snapshot in this PR jira
=> AMBARI-25975: Grafana upgrade to 9.x caused many issues in metrics grafana dashboards.

pom.xml
Upgrade to grafana-9.5.6 to fix CVEs
Built rpm, installed cluster and verified, it is working fine
=> AMBARI-25976: Upgrade grafana to remediate CVEs

ambari-metrics-timelineservice/src/main/java/org/apache/ambari/metrics/core/timeline/availability/MetricCollectorHAController.java
Show daily aggregate in summary API response
Applied changes to existing cluster, attached verification snapshot in this PR jira
=> AMBARI-25984: Ambari metrics summary API missing daily aggregator info

ambari-metrics-timelineservice/pom.xml
excluding snakeyaml to resolve CVEs
Testing on installing a local cluster.
=> [AMBARI-26184] Resolve snakeyaml 0.12 CVE

ambari-metrics-timelineservice/pom.xml
Upgrading ignite-core version to 2.1.0 to 2.15.0
Changes have been compiled and tested locally
=> AMBARI-25954 Upgrade ignite-core to 2.1.0 to 2.15.0

ambari-metrics-grafana/conf/unix/ams-grafana.ini, pom.xml
upgraded the grafana to latest 11.5.2
added flag to enable angular support for plugins
=> AMBARI-26324: Upgrade Grafana to latest 11.5.2 to resolve CVEs
